### PR TITLE
Fix Venti bug, added test and an extra message

### LINKED ISSUE #2: Venti Banner has issues
Venti being guaranteed has bugs after the last refactor, will need to be fixed.

### PR DESCRIPTION
**Pull request by lauslim12**
Hello!

This PR addresses the following:
- I have fixed the Venti bug. We should now properly get him if our first SSR is not Venti.
- Also added test suite for the guaranteed SSR after a non-Venti SSR pull.
- Added an additional disclaimer message on the modal that people should not expect this tool to be the reflection of their gacha experience, as some people are simply hopeless and believed that if they got an SSR here, then they would also get them in the game as well 😂 (even I sometimes hope so every time I get an SSR from the gacha simulator!).

Oh, and I think I found a bug:
- When we receive an SSR that is not from the 90 pull, I believe the `attemptsCount` variable is not reset to zero, which is the expected behavior from Genshin Impact's gacha. In other words, because of this bug, we are guaranteed to get an SSR every 90 `attemptsCount`, even if we had gained one SSR beforehand.
- But I also notice that you use the `attemptsCount` variable to take note about how much times we have pulled. I propose a fix and that is to create a new variable to store how many times we have pulled from the gacha pool, but it will be reset every time we pulled an SSR. 

Here is an example of the bug. As you can see, I have fixed it so the second SSR is Venti. However, if I tested it many times and added a `console.log` to print the drops to the screen, an SSR is always on the 90th pull, even if we had gained one SSR beforehand (please ignore the `true` and `false`, it's just I printed it to the console so I can see the variable values for easier debugging).
Capture4

I think I can fix that if you want, what do you think? I'll make another issue and another pull request, as they say that smaller PR's are better 😅.

Thank you very much!

Resolves #2

### CODE REVIEW

**Comment by uzair-ashraf** [comment]
Reviewing now, as for the bug you found, I may have not understood properly

> When we receive an SSR that is not from the 90 pull, I believe the attemptsCount variable is not reset to zero, which is the expected behavior from Genshin Impact's gacha. In other words, because of this bug, we are guaranteed to get an SSR every 90 attemptsCount, even if we had gained one SSR beforehand.

Are you saying that we should not get a guaranteed 5 star pull every 90 attempts? It states atleast once per 90 attempts
image

The setter in the class sets the guaranteed5Star property dynamically.

image

Ah I believe it makes sense now, you want to reset the attempts count after recieving a 5 star to make sure the guarantee follows through,

The attempts count is used in the tests to provide further expandability in the future as well.

If you do update it, you will have to test the app vigorously to make sure it works properly but I like the idea.

File: src/models/ballad-in-goblets.js [hunk 1]
```diff
@@ -42,16 +42,29 @@ export default class BalladInGoblets extends BaseGacha {
...
   }
   getRandomItem(rating) {
-    const itemsList = this.getDrops(rating)
-    const item = itemsList[this.generateRandomNumber(itemsList.length)]
+    const itemsList = this.getDrops(rating);
+    let item;
+
+    // If our previous SSR didn't drop a Venti, then this time, we'll get him.
+    if (this.guaranteedVenti && rating === 5) {
+      item = this.drops.find((el) => el.name === 'Venti');
```
Comment (uzair-ashraf) [inline src/models/ballad-in-goblets.js:50]: use the `grabAVenti` method here, and for the sake of consitency drop the paranthesis when using a single parameter in arrow functions.

File: test/test.js [hunk 2]
```diff
@@ -1,5 +1,6 @@
 const chai = require('chai')
 const { expect } = chai
+import { assert } from 'chai'
```
Comment (uzair-ashraf) [inline test/test.js:3]: No need to import if just needed once

File: test/test.js [hunk 3]
```diff
@@ -80,6 +81,49 @@ describe('Testing suite for genshin impact gacha', () => {
...
+        // Filter all the results by its five star.
+        // If there are any results, store its name in a new array for easier checking.
+        const filteredResults = results[results.length - 1].filter((item) => item.rating === 5);
+        const names = filteredResults.map((e) => e.name);
+        const areNamesFilled = names.length > 0 ? true : false;
+        
+        // This step will fail if the second SSR is not Venti.
+        // We'll also have to check if we pulled any SSR, hence the 'names.length' to prevent false negatives.
+        if (hasSSR && !names.includes('Venti') && areNamesFilled) {
+          assert.fail('The second SSR pulled was not Venti!');
```
Comment (uzair-ashraf) [inline test/test.js:106]: For the sake of consistency use `expect.fail` instead.

File: test/test.js [hunk 4]
```diff
@@ -80,6 +81,49 @@ describe('Testing suite for genshin impact gacha', () => {
...
+    it('should give a Venti after pulling an SSR that is not Venti (first Venti pull is also acceptable)', done => {
+      const results = [];
+      const balladVenti = new BalladInGoblets();
+      let hasVenti = false;
+      let hasSSR = false;
+
+      // Infinite loop, we want to keep pulling until we discovered a Venti.
+      while (true) {
+        results.push(balladVenti.roll());
+
```
Comment (uzair-ashraf) [inline test/test.js:96]:
```
const roll = balladVenti.roll()
results.push(roll)
```

File: test/test.js [hunk 5]
```diff
@@ -80,6 +81,49 @@ describe('Testing suite for genshin impact gacha', () => {
...
+      // Infinite loop, we want to keep pulling until we discovered a Venti.
+      while (true) {
+        results.push(balladVenti.roll());
+        
+        // Filter all the results by its five star.
+        // If there are any results, store its name in a new array for easier checking.
+        const filteredResults = results[results.length - 1].filter((item) => item.rating === 5);
+        const names = filteredResults.map((e) => e.name);
+        const areNamesFilled = names.length > 0 ? true : false;
```
Comment (uzair-ashraf) [inline test/test.js:101]: Drop paranthesis in one parameter arrow functions for the sake of consitency
```
        const filteredResults = roll.filter(item => item.rating === 5);
        const names = filteredResults.map(e => e.name);
        const areNamesFilled = names.length > 0;
```
No ternary needed, expressions using comparison operators always resolve to a boolean

**Review by uzair-ashraf — CHANGES_REQUESTED** [review]

**Comment by lauslim12** [comment]
Okay, code updated to your review! Thank you!

`Are you saying that we should not get a guaranteed 5 star pull every 90 attempts?`

I actually mean that the '90 attempt' counter should be reset if we pulled an SSR (because I notice a pattern where we'll get an SSR every 90 rolls, even if we had gotten an SSR in the middle of the count). I think Genshin Impact's gacha works like that? Every time we get an SSR, the counter will be reset back to zer.

`5-Star pity: If a player does not win a 5-star item 89 pulls in a row the 90th pull is guaranteed to be a 5-star item. This counter will reset if the player pulls any 5-star item.`

Source is from the [fandom wiki](https://genshin-impact.fandom.com/wiki/Wishes), but honestly, I actually believe that the gacha system is still extremely mysterious even to us...

File: test/test.js [hunk 6]
```diff
@@ -80,6 +80,50 @@ describe('Testing suite for genshin impact gacha', () => {
...
+      let hasSSR = false;
+
+      // Infinite loop, we want to keep pulling until we discovered a Venti.
+      while (true) {
+        const roll = balladVenti.roll();
+        results.push(roll);
+        
+        // Filter all the results by its five star.
+        // If there are any results, store its name in a new array for easier checking.
+        const filteredResults = results[results.length - 1].filter(item => item.rating === 5);
```
Comment (uzair-ashraf) [inline test/test.js:99]: Readability and helps make use of the roll variable 😅 
```
const filteredResults = roll.filter(item => item.rating === 5);
```

**Review by uzair-ashraf — CHANGES_REQUESTED** [review]
Thank you for contributing by the way I should have mentioned this before.
I can approve after this small change, You can create a separate pr for the attemptsCounter change afterwards, but you will have to update the tests as well.

**Comment by lauslim12** [comment]
You're welcome! I always love contributing in open source projects!

I think I'll read more about the gacha before contributing the `attemptsCounter` so I can get a clearer picture on it. Do I have to make a new issue?

Thank you!

**Comment by uzair-ashraf** [comment]
We'll hold off on it for now, till after I finish Klees banner and we can do a refactor.

**Review by uzair-ashraf — APPROVED** [review]
